# Generating arbitrary data

First thing that one need while experimenting with linear algebra library is having data of arbitrary shape, following octave methods are helpful in generating data to play with.
* `[ ]`
* `eye`
* `zeros` `ones`
* `ranges `
* `linspace`
* `magic`

For generating random data use

* `rand`

In [26]:
#Generating from constants
x = [1,2,3] # A Row vector
x = [1; 2; 3] # A Column vector, rows are separated by semicolons

x = zeros(4)

#Generating from a range start, stop, step=1
x = [1:10; 1:10]
x = [1,2;4,5;7,8]

#Generates evenly spaced specifed number of data points between 2 endpoints
a = 2; b = 10; n = 5; 
x = linspace(a,b,n) #creates n datapoints between a and b inclusive

#Generates a 3X3 magic matrix i.e one whole rows, columns and diagonals add up to same number
x = magic(3) 

#Generate random data of given shape
x = rand(2,3)

x = eye(3) #generates identity matrix


x =

   1   2   3

x =

   1
   2
   3

x =

   1   2
   4   5
   7   8

x =

   0   0   0   0
   0   0   0   0
   0   0   0   0
   0   0   0   0

x =

    1    2    3    4    5    6    7    8    9   10
    1    2    3    4    5    6    7    8    9   10

x =

    2    4    6    8   10

x =

   0.144838   0.997498   0.096283
   0.626361   0.676938   0.905862

x =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

x =

   8   1   6
   3   5   7
   4   9   2



# Dimensions
what *types* are for a general programming, *dimensions* are for numerical programming. Getting them right goes a long way in having a bug free program

In Octave

use `size` to know the dimensions

use `reshape` to modify the dimensions. 



In [25]:
size(eye(6,3))
x1 = zeros(5,3); #putting ; after statement stops the result being printed
x2 = ones(4,6)
x = [x1(:);x2(:)]; #put them in one big vector

#To get x2 from x
x2_again = reshape(x(16:39), 4,6)


ans =

   6   3

x2 =

   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   1

x2_again =

   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   1
   1   1   1   1   1   1



# Transpose

In [18]:
x = magic(4) 
x' # transpose
transpose(x)

x =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1

ans =

   16    5    9    4
    2   11    7   14
    3   10    6   15
   13    8   12    1

ans =

   16    5    9    4
    2   11    7   14
    3   10    6   15
   13    8   12    1



# Dot Product

In [62]:

x = magic(3)
r = eye(3)
r(1,2) = 1
s1=sum(sum(x .* r))

s2=sum(sum(x(r == 1)))

s3 = x*r
s3 = sum(s3(:))

x =

   8   1   6
   3   5   7
   4   9   2

r =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

r =

   1   1   0
   0   1   0
   0   0   1

s1 =  16
s2 =  16
s3 =

    8    9    6
    3    8    7
    4   13    2

s3 =  60


# Mean and Variance

In [71]:
X = [
1, 1, 1;
2, 2, 2;
3, 3, 3;
4, 4, 4;
]

[m, n] = size(X)

mean(X)'
var(X,1)'

X =

   1   1   1
   2   2   2
   3   3   3
   4   4   4

m =  4
n =  3
ans =

   2.5000
   2.5000
   2.5000

ans =

   1.2500
   1.2500
   1.2500



# Transforming vectors

In [72]:
p = [
0.25;
0.35;
0.90;
0.11;
0.22;
]

p < 0.2

p =

   0.25000
   0.35000
   0.90000
   0.11000
   0.22000

ans =

  0
  0
  0
  1
  0



In [69]:
w = np.array([1,1,1])
np.tanh(w)
w

array([ 0.76159416,  0.76159416,  0.76159416])